spring.application.name=msauth
spring.security.filter.dispatcher-types=async,error,request

# Puerto del microservicio
server.port=8081
msusuarios.url=${MSUSUARIOS_URL}
app.jwt.secret=${APP_JWT_SECRET}
app.jwt.expiration-ms=${APP_JWT_EXPIRATION_MS:900000}

# Charset
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true
